// ChocoPap-ANGULAR17/src/app/accueil/caroussel/navcarousel/navcarousel.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { RouterModule, RouterOutlet } from '@angular/router';
import { CommonModule } from '@angular/common';

/* IMPORT DES COMPONENTS PERSONNALISES ET SERVICES */
import { CarousselComponent } from '../caroussel.component';
import { DataService } from '../../../data.service';


@Component({
  selector: 'app-navcarousel',
  standalone: true,
  imports: [RouterModule, RouterOutlet, CommonModule, CarousselComponent],
  providers:[DataService],
  templateUrl: './navcarousel.component.html',
  styleUrl: './navcarousel.component.scss'
})


export class NavcarouselComponent {
    @Input () idSlideCarousel : number = 1;
    @Output () idSlideNav = new EventEmitter<number>() ;

  onPrev(){
    if (this.idSlideCarousel > 1){
      this.idSlideCarousel--
      this.idSlideNav.emit(this.idSlideCarousel)
    } else {
      this.idSlideCarousel = 3
      this.idSlideNav.emit(this.idSlideCarousel)
    }
  }

  onNext(){
    if (this.idSlideCarousel < 3){
      this.idSlideCarousel++
      this.idSlideNav.emit(this.idSlideCarousel)
    } else {
      this.idSlideCarousel = 1
      this.idSlideNav.emit(this.idSlideCarousel)
    }
  }

  onSelect(id:number)
  {
    this.idSlideCarousel = id ;
    this.idSlideNav.emit(this.idSlideCarousel)
  }
  
  sendIdSlide(){
    this.idSlideNav.emit(this.idSlideCarousel)
  }

}
<!-- CAROUSSEL NAV -->
<div id="carousel-thumbs" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="row mx-0 justify-content-center">
                <div id="carousel-selector-0" class="thumb col-4 col-sm-2 px-1 py-2" [ngClass]="{'selected': idSlideCarousel===1}" data-target="#crslChocoAccueil" (click)="onSelect(1)">
                    <img src="./assets/images/accueil1.jpg" class="img-fluid" alt="img">
                </div>
                <div id="carousel-selector-1" class="thumb col-4 col-sm-2 px-1 py-2" [ngClass]="{'selected': idSlideCarousel===2}" data-target="#crslChocoAccueil" (click)="onSelect(2)">
                    <img src="./assets/images/accueil2.jpg" class="img-fluid" alt="img">
                </div>
                <div id="carousel-selector-2" class="thumb col-4 col-sm-2 px-1 py-2" [ngClass]="{'selected': idSlideCarousel===3}" data-target="#crslChocoAccueil" (click)="onSelect(3)">
                    <img src="./assets/images/accueil3.jpg" class="img-fluid" alt="img">
                </div>
            </div>
        </div>
    </div>                    
    <div id="Navigation">
        <!-- CAROUSSEL BOUTON PREV -->
        <a class="carousel-control-prev" role="button" title="Précédent" (click)="onPrev()">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </a>

        <!-- CAROUSSEL BOUTON NEXT -->
        <a class="carousel-control-next" role="button" title="Suivant" (click)="onNext()">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </a>
    </div> 
</div> <!-- /CARROUSSEL NAV -->

// ChocoPAPViteJS/src/Components/Home/Caroussel/NavCarousel/NavCarousel.tsx
import "./NavCarousel.scss";

export const NavCarousel = ( ) =>
{
  return (
    <div id="carousel-thumbs" className="carousel slide" data-ride="carousel">
        <div className="carousel-inner">
            <div className="carousel-item active">
                <div className="row mx-0 justify-content-center">
                    <div id="carousel-selector-0" className="thumb col-4 col-sm-2 px-1 py-2" [ngClass]="{'selected': idSlideCarousel===1}" data-target="#crslChocoAccueil" (click)="onSelect(1)">
                        <img src="./assets/images/accueil1.jpg" className="img-fluid" alt="img">
                    </div>
                    <div id="carousel-selector-1" className="thumb col-4 col-sm-2 px-1 py-2" [ngClass]="{'selected': idSlideCarousel===2}" data-target="#crslChocoAccueil" (click)="onSelect(2)">
                        <img src="./assets/images/accueil2.jpg" className="img-fluid" alt="img">
                    </div>
                    <div id="carousel-selector-2" className="thumb col-4 col-sm-2 px-1 py-2" [ngClass]="{'selected': idSlideCarousel===3}" data-target="#crslChocoAccueil" (click)="onSelect(3)">
                        <img src="./assets/images/accueil3.jpg" className="img-fluid" alt="img">
                    </div>
                </div>
            </div>
        </div>                    
        <div id="Navigation">
            <a className="carousel-control-prev" role="button" title="Précédent" (click)="onPrev()">
                <span className="carousel-control-prev-icon" aria-hidden="true"></span>
            </a>

            <a className="carousel-control-next" role="button" title="Suivant" (click)="onNext()">
                <span className="carousel-control-next-icon" aria-hidden="true"></span>
            </a>
        </div> 
    </div>
  );
};
